name: Lint

on: [pull_request]

env:
  PLUGIN_NAME: dashboards-observability
  OPENSEARCH_DASHBOARDS_VERSION: "main"

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/Opensearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}
          path: OpenSearch-Dashboards

      - name: Checkout dashboards observability
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/${{ env.PLUGIN_NAME }}
          fetch-depth: 0

      - name: Get node and yarn versions
        working-directory: ${{ env.WORKING_DIR }}
        id: versions_step
        run: |
          echo "::set-output name=node_version::$(cat ./OpenSearch-Dashboards/.nvmrc | cut -d"." -f1)"
          echo "::set-output name=yarn_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.yarn).match(/[.0-9]+/)[0]")"

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions_step.outputs.node_version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install correct yarn version for OpenSearch Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions_step.outputs.yarn_version }}

      - name: Bootstrap the plugin
        working-directory: OpenSearch-Dashboards/plugins/${{ env.PLUGIN_NAME }}
        run: yarn osd bootstrap

      - name: Get list of changed files using GitHub Action
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Changed Files
        id: files
        run: |
          files_modified=$(cat ${HOME}/files_modified.json)
          files_added=$(cat ${HOME}/files_added.json)
          files_renamed=$(cat ${HOME}/files_renamed.json)
          files_deleted=$(cat ${HOME}/files_deleted.json)
          echo "::set-output name=files_modified::$files_modified"
          echo "::set-output name=files_added::$files_added"
          echo "::set-output name=files_renamed::$files_renamed"
          echo "::set-output name=files_deleted::$files_deleted"

      - name: Lint Changed Files
        run: |
          CHANGED_FILES="${{ steps.files.outputs.files_modified }}"
          echo "These are the files to be lint: $CHANGED_FILES"
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "Linting changed files..."
            IFS=' ' read -r -a FILES_TO_LINT <<< "$CHANGED_FILES"
            for file in "${FILES_TO_LINT[@]}"; do
              if [[ $file == *.js || $file == *.ts || $file == *.tsx ]]; then
                yarn lint "$file"
              fi
            done
          else
            echo "No matched files to lint."
          fi
        working-directory: OpenSearch-Dashboards/plugins/${{ env.PLUGIN_NAME }}
